Sprint 3
SweetAlcatel/middle.messenger.praktikum.yandex pull request #13
Opened 2023-02-11 13:59 UTC by SweetAlcatel

Из основного: нашел баг в событийной модели компонента block, пришлось переделывать, но вроде бы справился, данные подгружаются
остальное тривиально и по курсу

2023-02-12 12:52 UTC, podlovchenko requested changes
Привет, есть некоторые замечания
1. На нетлифае неактуальная версия
2. Нет редиректа если пользователь уже в системе
3. Нет работы с чатами
4. Нет валидации данных на странице авторизации/регистрации
5. Ссылки в приложении не рабочие
6. Нет возможности изменять аватар

2023-02-12 12:52 UTC, podlovchenko commented on src/controllers/chats.ts
> +      timeout: 3000,
Таймаут по умолчанию можно внести внутрь HttpTransport

2023-02-12 12:52 UTC, podlovchenko commented on src/controllers/chats.ts
> +      method: Methods.GET,
В методе get не надо дополнительно указывать метод GET

2023-02-12 12:52 UTC, podlovchenko commented on src/controllers/chats.ts
> +      },
Эту логику тоже можно внести внутрь HttpTransport

2023-02-12 12:52 UTC, podlovchenko commented on src/layout/chat/chat.hbs
> +        <span>Изображение</span>
В 3 спринте уже не должно остаться моковых данных

2023-02-12 13:16 UTC, SweetAlcatel commented on src/controllers/chats.ts
> +      },
Это заметил, спасибо
просто нет особо времени рефакторить, но логику переноса целиком и полностью понимаю

2023-02-12 15:02 UTC, SweetAlcatel commented on src/controllers/chats.ts
> +      method: Methods.GET,
понимаю целиком и полностью, что это можно грамотнее инкапсулировать

2023-02-12 15:44 UTC, SweetAlcatel commented on src/controllers/chats.ts
> +      timeout: 3000,
аналогично ниже написанному

2023-02-13 11:35 UTC, podlovchenko requested changes
Привет
1. Все еще нет валидации данных в формах
2. Нет работы с чатами
3. Ссылки также не работают (например "к профилю")
4. Нет редиректа, если пользователь в системе

2023-02-15 18:28 UTC, SweetAlcatel commented
За 4 дня переработал внушительную часть проекта, валидация работает через атрибут pattern с регулярными выражениями и стилями scss

2023-02-16 09:22 UTC, podlovchenko commented
Привет, ни локально, ни на нетлифай не вижу валидации, работы с чатами и тд

2023-02-17 20:51 UTC, SweetAlcatel commented
Я не понимаю почему не собирается пайплайн, у меня все локально окей запускается + нейминг корректен в этом месте

2023-02-17 20:53 UTC, SweetAlcatel commented
Будьте снисходительны, ради бога, я не сплю уже второй день, лишь бы уложиться в дедлайн

2023-02-18 12:48 UTC, SweetAlcatel commented
Если вы видите это сообщение, то знайте, лучше пока не смотреть, занимаюсь большим рефакторингом кода

2023-02-19 07:40 UTC, podlovchenko approved these changes
Спасибо за правки, работу принимаю)

2023-02-19 08:39 UTC, merged